# Generated by Django 5.2.7 on 2025-10-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='requested_by',
            field=models.ForeignKey(default='1', help_text='User who requested this organisation', on_delete=django.db.models.deletion.CASCADE, related_name='organisation_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
