# Generated by Django 5.2.7 on 2025-10-04 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organisation_approval_date_organisation_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('coordinator', 'Coordinator'), ('editor', 'Data Editor'), ('analyst', 'Data Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Job title within the organization', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Work email (if different from user email)', max_length=254)),
                ('is_public_contact', models.BooleanField(default=False, help_text='Show contact info publicly')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__first_name', 'user__last_name'],
                'unique_together': {('organisation', 'user')},
            },
        ),
    ]
